public class escapePatterns {
   public static void main(String[] args) {
    // Right half pyramid using Single print Statement...
    System.out.println("*\n* *\n* * *\n* * * *\n* * * * *");
// Here i am using the \t to provide the space between two output...
    System.out.println("\t");
    // Reverse Right Half Pyramid using Single print Statement...
    System.out.println("* * * * *\n* * * *\n* * *\n* *\n*");
    // Here i am using the \t to provide the space between two output...
    System.out.println("\t");
    // left half pyramid using single print Statement...
    System.out.println("        *\n      * *\n    * * *\n  * * * *\n* * * * *");
   } 
}
